project_id = "rjgyhdwakglxakmrkggg"

[functions.create-admin]
verify_jwt = false

[functions.reset-admin-password]
verify_jwt = false

[functions.generate-suggestions]
verify_jwt = false

[functions.track-usage]
verify_jwt = false

[functions.get-subscription]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.revamp-cv]
verify_jwt = false
